openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /blogpost:
    get:
      summary: 'blogpost() : this method shows the view of a blog creation form'
      description: "blogs are posts made by users that contain text writings. Each blog has a cover image on top\nas well. It also has an individual blog viewing page. User can share their written texts in the\nblogs."
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: '{ return \Illuminate\View\View }'
      tags:
        - 'BlogpostController class'
      security: []
    post:
      summary: 'store() : Stores a newly created blog post in storage'
      description: "This method stores the created blog post in the storage. It takes the parameter '$userId' from the route url.\nAll the data about that blog is stored inside a laravel 'Collection Object'.\nThe function returns a view of the 'single blog' page along with the 'Collection Object'\nwhich contains the blog data."
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: multipart/form-data
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: '{ return \Illuminate\View\View }'
      tags:
        - 'BlogpostController class'
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                'title ':
                  type: string
                  description: ''
                  example: consequatur
                text_writings:
                  type: string
                  description: 'The text description of the blog post. This can be a few paragraphs. This is main content of the blog post.'
                  example: eligendi
                cover_photo:
                  type: string
                  format: binary
                  description: 'The uploaded image file'
                title:
                  type: string
                  description: 'The title of the blog post.'
                  example: quisquam
              required:
                - 'title '
                - text_writings
                - cover_photo
                - title
      security: []
  '/single-blog/{blogId}':
    get:
      summary: 'blog() : Displays the view of an individual blog.'
      description: "An individual blog shows the contents of a blog from a user. The post needs to contain\na cover photo, title and the text descriptions for the main body of the blog."
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "{\n\"b_id\": 4,\n\"u_id\": 2,\n\"title\": \"Example\",\n\"cover_photo\": \"1640627401-username-CJ9.jpg\"\n \"text_writings\": \"This is an example text writing\",\n \"created_at\": \"2021-12-27 07:50:02\",\n \"updated_at\": \"2021-12-27 07:50:02\",\n}"
      tags:
        - 'BlogpostController class'
      security: []
    parameters:
      -
        in: path
        name: blogId
        description: 'The ID of the blog'
        example: 8
        required: true
        schema:
          type: integer
  '/follow/{followingUserId}':
    get:
      summary: 'followUser(): Allows a user to the follow another user.'
      description: "This method takes the parameter '$followingUserId' from the route url. This parameter\ncontains the 'user ID' of the user who is being followed by the current logged in user. The userId of the\ncurrent logged in user is saved in the variable '$followerUserId'.<br>\nThe user Id of the follower and the user Id of user who is being followed are added to the 'follower_list'\ntable of the database by using the 'FollowerList' model.<br>\nFinally, the user gets redirected to the page from which the follow request came from."
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: '{ return \Illuminate\View\View }'
      tags:
        - 'FollowController class'
      security: []
    parameters:
      -
        in: path
        name: followingUserId
        description: 'The Id of the user who is being followed.'
        example: 13
        required: true
        schema:
          type: integer
  '/unfollow/{unfollowingUserId}':
    get:
      summary: 'unfollowUser(): Allows a user to the unfollow another user.'
      description: "This method takes the parameter '$unfollowingUserId' from the route url. This parameter\ncontains the 'user ID' of the user who is being unfollowed by the current logged in user. The userId of the\ncurrent logged in user is saved in the variable '$followerUserId'.<br>\nThe row containing the user Id of the unfollower and the user Id of user who is being unfollowed\nis deleted 'follower_list' table of the database by using the 'FollowerList' model.<br>\nFinally, the user gets redirected to the page from which the unfollow request came from."
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: success
          content:
            text/plain:
              schema:
                type: string
                example: '{ return \Illuminate\View\View }'
      tags:
        - 'FollowController class'
      security: []
    parameters:
      -
        in: path
        name: unfollowingUserId
        description: 'The Id of the user who is being unfollowed.'
        example: 14
        required: true
        schema:
          type: integer
  /is-following:
    get:
      summary: 'isFollowing(): Checks if the logged-in user is following a certain user.'
      description: "This methods takes '$userId' as a parameter and checks if the logged in user\nis following that particular 'userId'. The function returns true if the logged-in\nuser is following a certain user and returns false if the user is not following\nthat certain user."
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: '{ return Boolean }'
      tags:
        - 'FollowController class'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                $userId:
                  type: integer
                  description: 'The user of a particular user.'
                  example: 20
              required:
                - $userId
      security: []
  '/follower-page/{userId}':
    get:
      summary: 'followerPage(): Displays a page containing the follower and following list of an user'
      description: "This method takes '$userId' as a parameter from the URL.This user id is of the user whos\nfollower/following page is being viewed.<br>\nThis is 'userId' is then used to find which user are following that userId and also to find\nwhich users are being followed by that userId.<br>\nFinally, the function returns a view of the 'followerpage' along with two collection\nobjects which contains the list of followers and the list of user being followed by\nthat particular userId."
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: '{ return \Illuminate\View\View }'
      tags:
        - 'FollowController class'
      security: []
    parameters:
      -
        in: path
        name: userId
        description: 'User Id of the user whos follower and following list is being displayed.'
        example: 17
        required: true
        schema:
          type: integer
  /newsfeed:
    get:
      summary: 'index(): Displays the view of the Newsfeed.'
      description: "This method returns the view of the newsfeed an user.<br>\nFirst, it finds the 'userId' of the logged in user from the Session variable.\nThen, that 'userId' is used to find all the users that user is following.\nUsing the list of users that were followed, this function retrieves\nall photos and blogs that were posted by those users. Data about about all the\nphotos and blogs are stored inside a laravel 'Collection Object'.<br>\nFinally, the method return the view of the 'newsfeed' page along with the 'Collection\nObject' which contains data about photos and blogs."
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: '{ return \Illuminate\View\View }'
      tags:
        - 'NewsfeedController class'
      security: []
  '/photo/{photoId}':
    get:
      summary: 'index(): Display the view of an individual photo.'
      description: "This method takes the parameter '$photoId' from the route url.\nThe '$photoId' is used to find the particular photo with the same photoId from the database.\nAll the data about that photo is stored inside a laravel 'Collection Object'.<br>\nFinally, the function returns a view of the 'photopage' along with the 'Collection Object'\nwhich contains the photo data."
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "{\n \"p_id\": 4,\n \"u_id\": 2,\n \"caption\": \"This is an example caption\",\n \"photo_path\": \"example-photo.jpg\",\n \"created_at\": \"2021-12-22 08:58:02\",\n \"updated_at\": \"2021-12-22 08:58:0\",\n}"
      tags:
        - 'PhotoController class'
      security: []
    parameters:
      -
        in: path
        name: photoId
        description: 'The ID of the photo'
        example: 16
        required: true
        schema:
          type: integer
  /photo-upload:
    post:
      summary: 'photoUpload(): Store a newly uplaoded photo in database.'
      description: "This method takes a form request parameter '$request' as a method parameter.\nThe '$request' parameter contains two parameters which contains the values that were submitted with\nthe 'photo upload form' and these two parameters are 'caption' and 'photo'.<br>\nHere, the method validates the form data received from the '$request' variable and returns error messages\nif the request fails to validate.\nThe uploaded image file is given a new name and stored in the storage.<br>\nNext, the method stores the necesary informations about the photo in the database by creating a\nnew row in the 'photos' table within the database.<br>\nFinally, it redirects the user to the page of the photo that was uploaded."
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: multipart/form-data
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: failure
          content:
            text/plain:
              schema:
                type: string
                example: '{ form data failed to validate }'
      tags:
        - 'PhotoController class'
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                caption:
                  type: string
                  description: 'The caption of the photo.'
                  example: dolor
                photo:
                  type: string
                  format: binary
                  description: 'The uploaded image file'
              required:
                - photo
      security: []
  /photo-upload-page:
    get:
      summary: 'photoUploadPage(): Display the view of the photo upload page.'
      description: "This method returns the view of the photo upload page where the users can\nupload photos."
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: '{ return \Illuminate\View\View }'
      tags:
        - 'PhotoController class'
      security: []
  '/photo-delete/{photoId}':
    delete:
      summary: 'photoDelete(): Deletes a photo from Database.'
      description: "This methods the parameter '$photoId' from the url, which is the\nphoto id of the photo the user requested to delete.<br>\nUsing this photo id the function finds the photo from the database\nand deletes all the information related to the photo from the database. It\nalso deletes the photo from the storage as well.<br>\nFinally, the function redirects the user to the view of the newsfeed page."
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: success
          content:
            text/plain:
              schema:
                type: string
                example: '{ return \Illuminate\View\View }'
      tags:
        - 'PhotoController class'
      security: []
    parameters:
      -
        in: path
        name: photoId
        description: 'The ID of the photo'
        example: 16
        required: true
        schema:
          type: integer
  /text-on-image:
    get:
      summary: 'textOnImage() : creates a watermark on the photo.'
      description: "This method creates a watermark on photo while uploading.\nFont can be customized and the position of the watermark can be\nchanged from this method as well."
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: '{ return \Illuminate\View\View }'
      tags:
        - 'PhotoController class'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                newImageName:
                  type: string
                  description: 'Name of the Image.'
                  example: ad
                userName:
                  type: string
                  description: 'Name of the user.'
                  example: omnis
              required:
                - newImageName
                - userName
      security: []
tags:
  -
    name: 'BlogpostController class'
    description: "\nThe methods inside this class are used for creating or \nviewing a single blog on this web application."
  -
    name: 'FollowController class'
    description: "\nThe methods inside this class are used for implemententing \nfeatures such as 'follow user', 'unfollow user' and 'display follower\nand following List'"
  -
    name: 'NewsfeedController class'
    description: "\nThe methods inside this class are used displaying the\nnewsfeed of an user."
  -
    name: 'PhotoController class'
    description: "\nThe methods inside this class are used for uploading or \nviewing a single photo on this web application."
